#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  setup.sh [options] <unicorn.whl>

Options:
  --work-dir DIR   Installation workspace. Default: $UNICORN_WORK_DIR,
                   then /mnt/data/unicorn-kit when /mnt/data exists,
                   otherwise ./.tools/unicorn
  --python CMD     Python interpreter to use. Default: python3
  --sha256 HEX     Expected SHA-256 for the wheel
  -h, --help       Show this help

The script never downloads Unicorn or Python packages from the network.
The supplied local wheel is installed with pip --no-index --no-deps.
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
log() { printf '[unicorn-setup] %s\n' "$*"; }

if [[ -n "${UNICORN_WORK_DIR:-}" ]]; then
  WORK_DIR=$UNICORN_WORK_DIR
elif [[ -d /mnt/data ]]; then
  WORK_DIR=/mnt/data/unicorn-kit
else
  WORK_DIR="$PWD/.tools/unicorn"
fi

PYTHON=python3
EXPECTED_SHA256=
WHEEL=

while (($#)); do
  case "$1" in
    --work-dir) (($# >= 2)) || die '--work-dir requires a value'; WORK_DIR=$2; shift 2 ;;
    --python) (($# >= 2)) || die '--python requires a value'; PYTHON=$2; shift 2 ;;
    --sha256) (($# >= 2)) || die '--sha256 requires a value'; EXPECTED_SHA256=${2,,}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *) [[ -z "$WHEEL" ]] || die 'only one wheel may be supplied'; WHEEL=$1; shift ;;
  esac
done

[[ -n "$WHEEL" ]] || { usage >&2; exit 2; }
[[ -f "$WHEEL" ]] || die "wheel not found: $WHEEL"
[[ "$WHEEL" == *.whl ]] || die "expected a .whl file: $WHEEL"
command -v "$PYTHON" >/dev/null || die "Python interpreter not found: $PYTHON"
command -v sha256sum >/dev/null || die 'sha256sum is required'

ACTUAL_SHA256=$(sha256sum "$WHEEL" | awk '{print $1}')
log "wheel: $(basename "$WHEEL")"
log "size: $(stat -c '%s' "$WHEEL") bytes"
log "SHA-256: $ACTUAL_SHA256"
if [[ -n "$EXPECTED_SHA256" && "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]]; then
  die "SHA-256 mismatch (expected $EXPECTED_SHA256)"
fi

mkdir -p "$WORK_DIR"
VENV_DIR="$WORK_DIR/venv"
ENV_FILE="$WORK_DIR/env.sh"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

log 'creating isolated Python environment'
rm -rf -- "$VENV_DIR"
"$PYTHON" -m venv "$VENV_DIR"

log 'installing Unicorn from the local wheel only (network disabled)'
"$VENV_DIR/bin/python" -m pip install \
  --disable-pip-version-check \
  --no-index \
  --no-deps \
  "$WHEEL"

cat > "$ENV_FILE" <<ENV
# Generated by unicorn/setup.sh
export UNICORN_VENV=$(printf '%q' "$VENV_DIR")
ENV

log 'running x86 emulation smoke test'
"$VENV_DIR/bin/python" -P "$SCRIPT_DIR/verify.py"

cat <<EOF

Setup complete.
  venv: $VENV_DIR
  env:  $ENV_FILE

Use:
  UNICORN_WORK_DIR=$(printf '%q' "$WORK_DIR") ./unicorn/python.sh your_script.py
EOF
