#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  setup.sh [options] <capstone.whl> <keystone_engine.whl>

Options:
  --work-dir DIR          Installation workspace. Default: $CAPSTONE_KEYSTONE_WORK_DIR,
                          then /mnt/data/capstone-keystone-kit when /mnt/data exists,
                          otherwise ./.tools/capstone-keystone
  --python CMD            Python interpreter to use. Default: python3
  --capstone-sha256 HEX   Expected SHA-256 for the Capstone wheel
  --keystone-sha256 HEX   Expected SHA-256 for the Keystone wheel
  -h, --help              Show this help

The script never downloads packages. Both supplied wheels are installed with
pip --no-index --no-deps and then verified with an assemble/disassemble smoke test.
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
log() { printf '[capstone-keystone-setup] %s\n' "$*"; }

if [[ -n "${CAPSTONE_KEYSTONE_WORK_DIR:-}" ]]; then
  WORK_DIR=$CAPSTONE_KEYSTONE_WORK_DIR
elif [[ -d /mnt/data ]]; then
  WORK_DIR=/mnt/data/capstone-keystone-kit
else
  WORK_DIR="$PWD/.tools/capstone-keystone"
fi

PYTHON=python3
CAPSTONE_SHA256=
KEYSTONE_SHA256=
CAPSTONE_WHEEL=
KEYSTONE_WHEEL=

while (($#)); do
  case "$1" in
    --work-dir) (($# >= 2)) || die '--work-dir requires a value'; WORK_DIR=$2; shift 2 ;;
    --python) (($# >= 2)) || die '--python requires a value'; PYTHON=$2; shift 2 ;;
    --capstone-sha256) (($# >= 2)) || die '--capstone-sha256 requires a value'; CAPSTONE_SHA256=${2,,}; shift 2 ;;
    --keystone-sha256) (($# >= 2)) || die '--keystone-sha256 requires a value'; KEYSTONE_SHA256=${2,,}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *)
      case "$(basename "$1")" in
        capstone-*.whl)
          [[ -z "$CAPSTONE_WHEEL" ]] || die 'multiple Capstone wheels supplied'
          CAPSTONE_WHEEL=$1
          ;;
        keystone_engine-*.whl|keystone-engine-*.whl)
          [[ -z "$KEYSTONE_WHEEL" ]] || die 'multiple Keystone wheels supplied'
          KEYSTONE_WHEEL=$1
          ;;
        *) die "could not classify wheel by filename: $1" ;;
      esac
      shift
      ;;
  esac
done

[[ -n "$CAPSTONE_WHEEL" ]] || die 'Capstone wheel is required'
[[ -n "$KEYSTONE_WHEEL" ]] || die 'Keystone wheel is required'
[[ -f "$CAPSTONE_WHEEL" ]] || die "wheel not found: $CAPSTONE_WHEEL"
[[ -f "$KEYSTONE_WHEEL" ]] || die "wheel not found: $KEYSTONE_WHEEL"
command -v "$PYTHON" >/dev/null || die "Python interpreter not found: $PYTHON"
command -v sha256sum >/dev/null || die 'sha256sum is required'

verify_hash() {
  local label=$1 path=$2 expected=$3 actual
  actual=$(sha256sum "$path" | awk '{print $1}')
  log "$label wheel: $(basename "$path")"
  log "$label size: $(stat -c '%s' "$path") bytes"
  log "$label SHA-256: $actual"
  if [[ -n "$expected" && "$actual" != "$expected" ]]; then
    die "$label SHA-256 mismatch (expected $expected)"
  fi
}

verify_hash Capstone "$CAPSTONE_WHEEL" "$CAPSTONE_SHA256"
verify_hash Keystone "$KEYSTONE_WHEEL" "$KEYSTONE_SHA256"

mkdir -p "$WORK_DIR"
VENV_DIR="$WORK_DIR/venv"
ENV_FILE="$WORK_DIR/env.sh"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

log 'creating isolated Python environment'
rm -rf -- "$VENV_DIR"
"$PYTHON" -m venv "$VENV_DIR"

log 'installing local wheels only (network disabled)'
"$VENV_DIR/bin/python" -m pip install \
  --disable-pip-version-check \
  --no-index \
  --no-deps \
  "$CAPSTONE_WHEEL" \
  "$KEYSTONE_WHEEL"

cat > "$ENV_FILE" <<ENV
# Generated by capstone-keystone/setup.sh
export CAPSTONE_KEYSTONE_VENV=$(printf '%q' "$VENV_DIR")
ENV

log 'running Keystone -> Capstone smoke test'
"$VENV_DIR/bin/python" -P "$SCRIPT_DIR/verify.py"

cat <<EOF

Setup complete.
  venv: $VENV_DIR
  env:  $ENV_FILE

Use:
  CAPSTONE_KEYSTONE_WORK_DIR=$(printf '%q' "$WORK_DIR") ./capstone-keystone/python.sh your_script.py
EOF
